remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: The Accelarator
description: Catalogue of Function Apps to carry out different Tasks. Find yours
